### ISSUE TITLE
Logging events outside of connections

### ISSUE THREAD

**Issue by huitema** [quiclog/internet-drafts#106] opened 2020-07-10 20:15 UTC
Servers typically notice events happening outside of connections: packets for which the DCID is not recognized, malformed Initial packets, etc. When debugging and looking at both client traces and server traces, it might be useful to match a client packet with an out-of-connection event at the server. I wonder how to do that within the qlog framework.

**Comment by marten-seemann** [comment] 2020-07-11 01:34
I encountered the same issue. I think the root of the problem is that qlog is not streamable. Otherwise, you could just have a `server.qlog` and append every event that's not matched to any connection.

Sure, you can always play some tricks to work around this issue, like exporting a server qlog every one hour, for example. Downside is, of course, that you wouldn't have access to the events that happened with the last hour.

Broadening the scope of this issue, I'd say the root cause is that qlog is trying to make it possible to have multiple traces per file. Sure, it's possible, but only by giving up on streamability. I'm not sure if that's a feature worth having though, considering how much complexity it creates for the format itself (and for parsers that want to support it). I'd actually prefer to have a format that looks something like this:
```
<header>
   config options, vantage, other trace-related metadata
</header>
<events>

<events>
```

**Comment by rmarx** [comment] 2020-07-11 16:12
So, here again (like with #105, which I see as similar to this, maybe read my reply there first) I'm not sure what the issue is.

If an event cannot be matched to a connection, it's difficult to log it together with other events without keeping extra state and doing some work. That is usually relatively easy though: you can e.g., match IP+port of a malformed initial to other proper packets from the same source and aggregate them in the same trace based on that. Then you do need to add extra logic for migration etc. but it's certainly possible I'd say? 

Another option is as @marten-seemann mentions to have a single big `server.qlog' that includes all the events that don't nicely match to a connection (this could also include things you reply to with a version negotiation for example). I think Lars does this for quant. To me, it depends on how you want to debug your setup and how you approach these types of errors. I'm not sure if there needs to be more text on this? 

-----------

I am however unsure about why this `server.qlog` wouldn't be possible with the JSON-based setup... each qlog event is self-contained (it's a single array with some values and in draft-02 will be a single object) and can trivially be appended to a file by prepending it with a `,`. 

The thing that makes a JSON file that was "streamed" a bit more awkward is that you'd need to close it with a `]}]}' to be "valid JSON". However, qvis for example includes a fallback to a streaming parser (http://oboejs.com) to deal with files that don't do this and it seems to work perfectly fine (was initially added for cases where the endpoint shuts down unexpectedly and doesn't have time to print those final closing characters). Furthermore, this case is trivially fixed by a post-processor that adds those characters if they're not found at the end of a file. 

Am I missing something crucial in this discussion on streaming? Several people have brought this up (e.g., @martinthomson) but I have always considered this a non-issue. If we were switch to e.g., a csv-format, you'd have to write custom parsers for that as well (which would likely be slower than optimized, built-in JSON parsers), while now at least you get a free JSON parser if your files are well-formed (which, from my experience, most are or can be made to be). 

I also don't agree this is due to having support for multiple traces in one file. You can have just a single trace and use `group_id' to split things out later. The only thing this adds is the extra `]}`. Even if we left that out and stayed with JSON, you'd still be stuck with the other `]}' to close the `<events>` list and total object. 

Finally, especially for @marten-seemann, these might be moot points for draft-02, as that should make it much easier to use protobufs or similar instead of JSON. Still, I'd love some feedback on my points above, to make sure I'm not missing a key point in this discussion.

**Comment by marten-seemann** [comment] 2020-07-12 02:32
> I am however unsure about why this server.qlog wouldn't be possible with the JSON-based setup... each qlog event is self-contained (it's a single array with some values 

I'm not sure if I understand your point. I thought this is not the case. You can have multiple traces per file, so you'd have a file where events are appended at different locations within that file.
This is why I suggested getting rid of this corner case by saying that `1 qlog file == 1 trace`. That would simplify things quite a bit.

> Am I missing something crucial in this discussion on streaming? Several people have brought this up (e.g., @martinthomson) but I have always considered this a non-issue.

I'd be curious to hear what other peoples' requirements are here.
For me, streaming means that you have a valid at any given moment. With the qlog format that's not possible since you'll always be missing some closing `]` and `}`.
Imagine you want to build a tool like the UNIX command line utility `tail` for qlog, which outputs events as soon as they come in. This would be hard to do, as you're dealing with invalid JSON most of the time. 
Things are further complicated by the fact that JSON doesn't define the order of the fields within an object (for example, it would be valid qlog if `common_fields` comes after the `events`, and iirc, I've seen at least one qlog implementation write files like that).

>  If we were switch to e.g., a csv-format, you'd have to write custom parsers for that as well (which would likely be slower than optimized, built-in JSON parsers), while now at least you get a free JSON parser if your files are well-formed (which, from my experience, most are or can be made to be).

When I think of slow encoders, I think of JSON...
That being said, I don't think JSON buys us a lot here. The fact that qlogs have `common_fields` and `event_fields`, and that events are not exported as objects but as arrays makes it quite cumbersome to write a qlog exporter / parser. As I understand, the `event_fields` are effectively an attempt to build in some compression into the format, an attempt rendered moot by the fact that JSON is an inherently space-inefficient file format. gzipping a tyical qlog gives you a file smaller than 10% of the original file size... so I can't help to think of this as a premature optimization.

**Comment by huitema** [comment] 2020-07-12 02:37
+1 on premature optimization. I tripped on the event_fields when writing a python parser for the qlogs, and I see that others have similar issues. If you want to reduce volume, it would be simpler to just have shorter names for the variables.

**Comment by huitema** [comment] 2020-07-12 03:09
+1 on format too. I would very much like to be able to just add an event by appending the data at the end of the log file. I can do that with my binary logs, and then call a converter to produce the qlog and add the required set of curly and square brackets at the end. But with an actual qlog file, I would have to roll back the end of the file, remove the end brackets, write the event, and then add the brackets again. Kind of, not funny.

**Comment by rmarx** [comment] 2020-09-05 16:18
I believe this was resolved with the introduction of the streaming NDJSON option (discussed in #109) and other options I outlined in https://github.com/quiclog/internet-drafts/issues/106#issuecomment-657087933. If not, feel free to re-open.

**Closed by rmarx** 2020-09-05 16:18 UTC
