### ISSUE TITLE
revisit connection_state_updated

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/internet-drafts#78] opened 2020-04-12 04:01 UTC
I see the following problems with the `connection_state_updated` event:
1. `attempted` seems to be a duplicate of `connection_started` for the client (i.e. the two events would always be emitted at the same time)
2. `reset` is impossible to log. You send a stateless reset if you lost state for a connection (after a crash or reboot, or if a packet was misrouted to the wrong backend server). In any case, there’s no connection state to update by definition.
3. `handshake` seems to be a duplicate of connection_started for both sides.

I think these events could be removed without losing any information in the log.

I suggest adding a new event for [confirmation of the handshake](https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#name-handshake-confirmed). Maybe it would make sense to rename `active` to `handshake_completed` and add a `handshake_confirmed`?

**Comment by rmarx** [comment] 2020-04-12 11:31
Potential duplicate of #49, should be handled together. 

(meaning that, yes, this should be handled for -02)

**Comment by rmarx** [comment] 2020-04-12 12:11
After some thinking, I feel it might worthwhile to see if we can transform `connection_started` into a `parameters_set` equivalent for the `connectivity` category.

**Comment by marten-seemann** [comment] 2020-04-12 12:16
Adding to my list, `keepalive` should probably not be a connection state. The QUIC specification doesn't  say a lot about keep-alives other than you can send a packet once in a while if you have nothing else to send.
Maybe it's enough to set this as a `trigger` on the `packet_sent` event?

**Comment by rmarx** [comment] 2020-04-20 15:45
@marten-seemann just reported on the list that a separate `connection_closed` event would be interesting to log the reason the connection was closed (for which we're now either relying on the CONNECTION_CLOSE frame contents or an (internal_)error event). 

It seem like adding a `reason` field to `connection_state_updated` would work there too.
Alternatively, this could be part of the envisioned `parameters_set` connectivity event that would replace both separate `connection_started` and `connection_close` semantics, though I'd feel a bit uneasy putting a `reason` field in `parameters_set` (semantics seem off).  

Best to take a step back and look at this from a higher viewpoint to see if making all this generic gives us more benefits than simply having separate events for everything.

**Comment by marten-seemann** [comment] 2020-07-27 04:18
Here's my suggestion for a better `connection_state_updated` definition:
```
enum ConnectionState {
    client_address_verified, // when the server considers the client's source address verified
    handshake_complete, // handshake completed
    handshake_confirmed, // handshake confirmed
    draining, // CONNECTION_CLOSE sent
    closed // connection actually fully closed, memory freed
}
```

I added a `client_address_verified` to my earlier suggestion, since with https://github.com/quicwg/base-drafts/pull/3924, servers can make this decision based on multiple different criteria.

@rmarx What do you think?

**Comment by huitema** [comment] 2020-08-02 00:25
I like splitting `active` into `handshake_complete` and `handshake_confirmed` as @marten-seemann is suggesting above, and I also like `client address verified` as an intermediate server state. On the client side, I would like to see logging of the transition between `started` and `heard_from_the_server`, which is pretty much the client equivalent of `client_address_verified`.

On the other hand, all these states can be trivially deduced from observing the packet flow. @rmarx is the connection_state event really useful?

**Comment by rmarx** [comment] 2020-08-02 10:37
I have to re-read the draft myself first, but a merge of Marten's proposal (with a "started" state or similar put back in) and Christian's suggestion of `heard_from_server` seems sensible at first glance.

With regards to "do we need this event at all"... it depends. If you're logging all packets: potentially not, though that might hide implementation bugs (state transfer too early/late). However, as @marten-seemann has also said wrt a separate `connection_closed` event (instead of simply watching the `connection_state_updated` for this) and the discussion on needing a `packet_acked` event (#107): when writing tools that try to quickly deduce these state transitions from a trace, it can be useful to have these "duplicate" events as well. I don't think I'd write many tools that fully rely on only these myself, and I wouldn't mark them as "core" events in the spec, but I can see why some people like to keep them in and have a preference for this myself as well (up to a certain point...)

**Comment by rmarx** [comment] 2020-10-31 14:00
Related to #43

**Comment by rmarx** [comment] 2020-11-02 20:37
Closing this and moving to #43 as the main tracking issue for this.

**Closed by rmarx** 2020-11-02 20:37 UTC
Labels: current-version
